cn:
  spark2fire:
    auth:
      jwt:
        secretKey:

server:
  error:
    include-message: always

spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: validate
      use-new-id-generator-mappings: true
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/notebook?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: username
    password: password

---
spring:
  config:
    activate:
      on-profile: production

server:
  address: 127.0.0.1
  port: 6666
  compression:
    enabled: true
    min-response-size: 524288

logging:
  level:
    ROOT: INFO
