cn:
  spark2fire:
    auth:
      jwt:
        secretKey:

server:
  error:
    include-message: always

spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: validate
      use-new-id-generator-mappings: true
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/notebook?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: username
    password: password
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

---
spring:
  config:
    activate:
      on-profile: production

server:
  address: 127.0.0.1
  port: 6666
  compression:
    enabled: true
    min-response-size: 524288

logging:
  level:
    ROOT: INFO
